export const SET_KEPPER_LIST = "SET_KEPPER_LIST";
export const RESET_KEPPER_LIST = "RESET_KEPPER_LIST";

export const SET_SPECIFIC_KEEPER = "SET_SPECIFIC_KEEPER";
export const RESET_SPECIFIC_KEEPER = "RESET_SPECIFIC_KEEPER";

export const SET_COLLECTION_CHARGES = "SET_COLLECTION_CHARGES";
export const RESET_COLLECTION_CHARGES = "RESET_COLLECTION_CHARGES";
export const SET_PACKAGE_TYPES = "SET_PACKAGE_TYPES";
export const RESET_PACKAGE_TYPES = "RESET_PACKAGE_TYPES";
export const SET_CREATE_PACKAGE_TYPES = "SET_CREATE_PACKAGE_TYPES";
export const RESET_CREATE_PACKAGE_TYPES = "RESET_CREATE_PACKAGE_TYPES";
export const SET_SEARCH_OTP = "SET_SEARCH_OTP";
export const RESET_SEARCH_OTP = "RESET_SEARCH_OTP";

export const SET_STORE_LIST = "SET_STORE_LIST";
export const RESET_STORE_LIST = "RESET_STORE_LIST";

export const SET_SPECIFIC_STORE = "SET_SPECIFIC_STORE";
export const RESET_SPECIFIC_STORE = "RESET_SPECIFIC_STORE";
export const SET_SPECIFIC_PACKAGE_ID = "SET_SPECIFIC_PACKAGE_ID";
export const RESET_SPECIFIC_PACKAGE_ID = "RESET_SPECIFIC_PACKAGE_ID";

export const SET_PROVINCE_LIST = "SET_PROVINCE_LIST";
export const RESET_PROVINCE_LIST = "RESET_PROVINCE_LIST";

export const SET_SPECIFIC_PROVINCE = "SET_SPECIFIC_PROVINCE";
export const RESET_SPECIFIC_PROVINCE = "RESET_SPECIFIC_PROVINCE";

export const SET_ZONE_LIST = "SET_ZONE_LIST";
export const RESET_ZONE_LIST = "RESET_ZONE_LIST";

export const SET_SPECIFIC_ZONE = "SET_SPECIFIC_ZONE";
export const RESET_SPECIFIC_ZONE = "RESET_SPECIFIC_ZONE";

export const SET_City_LIST = "SET_City_LIST";
export const RESET_City_LIST = "RESET_City_LIST";

export const SET_SPECIFIC_City = "SET_SPECIFIC_City";
export const RESET_SPECIFIC_City = "RESET_SPECIFIC_City";

export const SET_NEIGHBORHOOD_LIST = "SET_NEIGHBORHOOD_LIST";
export const RESET_NEIGHBORHOOD_LIST = "RESET_NEIGHBORHOOD_LIST";

export const SET_SPECIFIC_NEIGHBORHOOD = "SET_SPECIFIC_NEIGHBORHOOD";
export const RESET_SPECIFIC_NEIGHBORHOOD = "RESET_SPECIFIC_NEIGHBORHOOD";

export const SET_CLIENT_LIST = "SET_CLIENT_LIST";
export const RESET_CLIENT_LIST = "RESET_CLIENT_LIST";

export const SET_SPECIFIC_CLIENT = "SET_SPECIFIC_CLIENT";
export const RESET_SPECIFIC_CLIENT = "RESET_SPECIFIC_CLIENT";

export const SET_COURIER_LIST = "SET_COURIER_LIST";
export const RESET_COURIER_LIST = "RESET_COURIER_LIST";

export const SET_SPECIFIC_COURIER = "SET_SPECIFIC_COURIER";
export const RESET_SPECIFIC_COURIER = "RESET_SPECIFIC_COURIER";

export const SET_AGREEMENT_LIST = "SET_AGREEMENT_LIST";
export const RESET_AGREEMENT_LIST = "RESET_AGREEMENT_LIST";

export const SET_CUSTOMERCARE_LIST = "SET_CUSTOMERCARE_LIST";
export const RESET_CUSTOMERCARE_LIST = "RESET_CUSTOMERCARE_LIST";

export const SET_CASHIER_LIST = "SET_CASHIER_LIST";
export const RESET_CASHIER_LIST = "RESET_CASHIER_LIST";

export const SET_ACCOUNTANT_LIST = "SET_ACCOUNTANT_LIST";
export const RESET_ACCOUNTANT_LIST = "RESET_ACCOUNTANT_LIST";
