export const SET_STATS = "SET_STATS";
export const RESET_STATS = "RESET_STATS";
export const SET_STATS_BY_MONTHS = "SET_STATS_BY_MONTHS";
export const RESET_STATS_BY_MONTHS = "RESET_STATS_BY_MONTHS";
export const SET_KEEPER_STATS = "SET_KEEPER_STATS";
export const RESET_KEEPER_STATS = "RESET_KEEPER_STATS";
export const SET_KEEPER_STATS_BY_MONTHS = "SET_KEEPER_STATS_BY_MONTHS";
export const RESET_KEEPER_STATS_BY_MONTHS = "RESET_KEEPER_STATS_BY_MONTHS";
