export const SET_ALL_ORDER = "SET_ALL_ORDER";
export const RESET_ALL_ORDER = "RESET_ALL_ORDER";
export const SET_TRACK_ORDER = "SET_TRACK_ORDER";
export const RESET_TRACK_ORDER = "RESET_TRACK_ORDER";
export const SET_ORDER_BY_STATUS = "SET_ORDER_BY_STATUS";
export const RESET_ORDER_STATUS = "RESET_ORDER_STATUS";
